name: "Jura S8 Price Tracker (MQTT)"
version: "0.0.7"
slug: "jura_s8_price_addon"
description: "Scrape prijzen voor Jura S8 bij diverse winkels en publiceer via MQTT Discovery als sensoren met historie."
url: https://github.com/svenkortekaas/jiras8pricetracker/tree/main/jura_s8_price_addon
arch:
  - amd64
  - aarch64
  - armv7
startup: services
init: false
boot: auto
panel_icon: mdi:coffee
map:
  - config:rw
ingress: false
homeassistant_api: false

options:
  # Kies EEN van beide: run_time OF scan_interval
  # run_time heeft voorrang; formaat HH:MM (24-uurs)
  run_time: "06:00"
  scan_interval: 1800
  base_topic: jura_s8
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  sites:
    - id: coolblue
      title: "Coolblue"
      url: "https://www.coolblue.nl/product/947474/jura-s8-piano-black-eb.html"
    - id: koffieloods
      title: "Koffie Loods"
      url: "https://www.koffie-loods.nl/jura-koffiemachines/jura-s8-piano-black-eb-gratis-proefpakket"
    - id: like2cook
      title: "Like2Cook"
      url: "https://www.like2cook.nl/jura-s8-piano-black-eb-15482"
    - id: voskoffie
      title: "Vos Koffie"
      url: "https://www.voskoffie.nl/webshop/jura-assortiment/jura-thuis/jura-s8-piano-black-eb/"
    - id: koffiestore
      title: "Koffiestore"
      url: "https://koffiestore.nl/products/jura-s8-piano-black-eb"
    - id: dekoffiewinkel
      title: "DeKoffieWinkel"
      url: "https://www.dekoffiewinkel.com/s8-piano-black-eb/"
    - id: mediamarkt
      title: "MediaMarkt"
      url: "https://www.mediamarkt.nl/nl/product/_jura-s8-eb-volautomatische-espressomachine-piano-black-1809815.html"
      title: "Ludiqx"
      url: "https://www.ludiqx.nl/products/jura-s8"

schema:
  run_time: str?
  scan_interval: int(30,86400)
  base_topic: str
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  sites:
    - id: str
      url: url
      title: str?
